services:
  postgres:
    image: postgres:18-alpine
    ports:
      - 9667:5432
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=65465
      - POSTGRES_USER=mc
      - POSTGRES_DB=stationofdoom