package de.j.deathMinigames.commands;

public enum ArgsLength1 {
    SETTINGS,
    LOWERDIFFICULTY,
    INTROPLAYERDECIDESTOUSEFEATURES,
    INTROPLAYERDECIDESTONOTUSEFEATURES,
    SETNOTINTRODUCED,
    DIFFICULTY,
    SETWAITINGLISTPOSITION,
    DECIDEDNOTTOSETPOSITION,
    STATUS,
    START,
    IGNORE
}