package de.j.deathMinigames.settings;

public enum InventoryMenus {
    INTRODUCTION,
    DIFFICULTY,
    USES_PLUGIN,
    DIFFICULTY_SETTINGS,
    SETTINGS,
    SETUP,
    PARKOUR_START_HEIGHT,
    PARKOUR_LENGTH,
    COST_TO_LOWER_THE_DIFFICULTY,
    TIME_TO_DECIDE_WHEN_RESPAWNING
}