name: Repo

on:
  release:
    types: [published, edited, released]

jobs:
  createRepo:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == false }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 21
          distribution: 'adopt'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4.4.1
      - name: Set env variables
        run: |
          echo "REPOSILITE_USER=${{ secrets.REPOSILITE_USER }}" >> $GITHUB_ENV
          echo "REPOSILITE_PW=${{ secrets.REPOSILITE_PW }}" >> $GITHUB_ENV
      - name: Publish
        run: |
          ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.REPOSILITE_USER }}
          MAVEN_PASSWORD: ${{ secrets.REPOSILITE_PW }}
